---
- hosts: server
  become: true
  pre_tasks:
    - name: Ensure dpkg is configured
      raw: sudo dpkg --configure -a
      ignore_errors: yes
      changed_when: false

    - name: Install Python pip
      apt:
        name: python3-pip
        state: present
      become: true

    - name: install update and repositories
      tags: always
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      changed_when: false

    - name: Install Docker SDK for Python
      pip:
        name: docker
      become: true

- hosts: server
  become: true
  roles:
    - role: Docker_auto-update
